innitial-commit-scope-of-project
front-end-by-rimantas/30-grupe-portfolio-docland pull request #27
Opened 2021-08-20 11:40 UTC by RimantasZiedelis

2021-08-20 11:54 UTC, belauzas requested changes
Komentarai turi būti aplink kodą
```
<!--Footer pradzia -->
<footer>
</footer>
<!--Footer pabaiga -->
```
bei, kiekviena sekcija turėtų naudoti tinkamesnius tag'us: <header>, <section> ar <footer>

2021-08-20 11:54 UTC, belauzas requested changes

2021-08-20 11:54 UTC, belauzas commented on index.html
> +      CONTENT>
nereikalingas tekstas - ištrinti

2021-08-20 11:55 UTC, RimantasZiedelis commented on index.html
> +      CONTENT>
ok

2021-08-20 11:55 UTC, belauzas requested changes

2021-08-20 11:55 UTC, belauzas commented on index.html
>      <script src="./js/home.js" type="module" defer></script>
<script> tag'as keliauja į galą, prieš pat turinio uždarymą, t.y. </body>

2021-08-20 12:13 UTC, RimantasZiedelis commented on index.html
>      <script src="./js/home.js" type="module" defer></script>
Sutvarkiau, ?

2021-08-20 14:00 UTC, belauzas requested changes

2021-08-20 14:00 UTC, belauzas commented on index.html
> +    </div>
ar šitas tag'as reikalingas?

2021-08-20 14:29 UTC, RimantasZiedelis commented
Div'us pakeisim kitais tagais procese. Mums, tiesiog,reikia pajudėti iš vietos.

2021-08-20 15:37 UTC, Algis1978 approved these changes

2021-08-20 17:43 UTC, belauzas commented
12 ir 80 eilutės vis dar turi nereikalingus tag'us

2021-08-22 09:41 UTC, egidijusguobis approved these changes

2021-08-22 19:46 UTC, RimantasZiedelis reviewed
ok

2021-08-22 19:46 UTC, RimantasZiedelis commented on index.html
> +    </div>
Nežinau : (

2021-08-22 19:47 UTC, closed without merging