Basic structure
front-end-by-rimantas/30-grupe-portfolio-docland pull request #29
Opened 2021-08-22 12:21 UTC by egidijusguobis

Idetas logo img.png ir padaryta siokia tokia structura naudojant duota base/layout.css

2021-08-22 19:25 UTC, RimantasZiedelis approved these changes

2021-08-23 07:56 UTC, Algis1978 approved these changes

2021-08-24 10:11 UTC, eMeS-Dev approved these changes

2021-08-24 10:20 UTC, eMeS-Dev requested changes
This branch has conflicts that must be resolved:
Conflicting files
css/base/layout.css
index.html

2021-08-24 10:32 UTC, eMeS-Dev approved these changes

2021-08-24 10:33 UTC, Algis1978 approved these changes

2021-08-24 10:38 UTC, merged